# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and Push an image webapp
      inputs:
        command: 'buildAndPush'
        containerRegistry: 'dockerRomancadete'
        repository: 'romancadete/netcore-bookstore'
        dockerfile: '$(Build.SourcesDirectory)/BookStoreWebApp/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build and Push an image api
      inputs:
        command: 'buildAndPush'
        containerRegistry: 'dockerRomancadete'
        repository: 'romancadete/book-api'
        dockerfile: '$(Build.SourcesDirectory)/BookStoreWebApp/Dockerfile'
        tags: |
          $(tag)
