apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: book-store
spec:
  replicas: 2
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: book-store
        service: webapp
    spec:
      containers:
        - name: webapp
          image: romancadete/netcore-bookstore:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: BookStoreApiBaseAddress
              value: http://book-api/
            - name: BookstoreDatabaseSettings__ConnectionString
              value: mongodb://rrodriguez:N@v@l.2021@cluster0-shard-00-00.eozgy.mongodb.net:27017,cluster0-shard-00-01.eozgy.mongodb.net:27017,cluster0-shard-00-02.eozgy.mongodb.net:27017/BookstoreDb?ssl=true&replicaSet=atlas-1rxc7q-shard-0&authSource=admin&retryWrites=true&w=majority
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: book-store
    service: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: webapp