apiVersion: v1
kind: Service
metadata:
  name: bookstore-demonetcore
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "bookstore-demonetcore"
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: bookstore-demonetcore

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-demonetcore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore-demonetcore
  template:
    metadata:
      labels:
        app: bookstore-demonetcore
    spec:
      containers:
      - image: romancadete/netcore-bookstore:373
        name: bookstore-demonetcore
        ports:
          - containerPort: 80