apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookApi
  labels:
    app: book-store
spec:
  replicas: 1
  selector:
    matchLabels:
      service: bookApi
  template:
    metadata:
      labels:
        app: book-store
        service: bookApi
    spec:
      containers:
        - name: bookApi
          image: romancadete/book-api:373
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: bookApi
  labels:
    app: book-store
    service: bookApi
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: bookApi